name: Build and Push HAProxy with QUIC for ARM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        platforms: linux/arm/v7
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/haproxy-quic-arm:latest
        file: ./Dockerfile

    - name: Set output
      run: echo "image=${{ secrets.DOCKERHUB_USERNAME }}/haproxy-quic-arm:latest" >> $GITHUB_OUTPUT
      id: image

    - name: Use output
      run: echo "The published image is ${{ steps.image.outputs.image }}"
